version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: posledne
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
volumes:
  db_data:
